Repository fing9/whoami, pull requests merged in 2024-08, with the labels that each got.

#3 [Feat]: Spring Security를 이용한 카카오 소셜 회원 관리 기능 추가
  src/main/java/com/dahhong/whoami/auth/adapter/in/KakaoOauthController.java
  src/main/java/com/dahhong/whoami/auth/adapter/in/dto/KakaoCallbackResponseDto.java
  src/main/java/com/dahhong/whoami/auth/application/port/in/KakaoTokenRefreshUseCase.java
  src/main/java/com/dahhong/whoami/auth/application/port/in/LoginKakaoUseCase.java
  src/main/java/com/dahhong/whoami/auth/application/service/KakaoTokenRefreshService.java
  src/main/java/com/dahhong/whoami/auth/application/service/LoginKakaoService.java
  src/main/java/com/dahhong/whoami/auth/application/service/UserDetailsServiceImpl.java
  src/main/java/com/dahhong/whoami/auth/application/service/dto/TokenRefreshResponseDto.java
  src/main/java/com/dahhong/whoami/auth/domain/entity/UserDetailsImpl.java
  src/main/java/com/dahhong/whoami/global/config/KaKaoRestTemplateConfig.java
  src/main/java/com/dahhong/whoami/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dahhong/whoami/global/exception/customException/AuthorizationFailureException.java
  src/main/java/com/dahhong/whoami/global/response/enums/ResultCode.java
  src/main/java/com/dahhong/whoami/global/security/SecurityConfig.java
  src/main/java/com/dahhong/whoami/global/security/authenticationProvider/KakaoAuthenticationProvider.java
  src/main/java/com/dahhong/whoami/global/security/filter/KakaoJwtAuthenticationFilter.java
  src/main/java/com/dahhong/whoami/global/security/filter/dto/AccessTokenVerificationResponseDto.java
  src/main/java/com/dahhong/whoami/user/application/service/JoinKakaoUserService.java
  src/main/java/com/dahhong/whoami/user/domain/entity/Role.java
  src/main/java/com/dahhong/whoami/user/domain/entity/User.java
Labels: enhancement

#4 [Doc]: Swagger를 이용한 Kakao OAuth 관련 API 문서화
  build.gradle
  src/main/java/com/dahhong/whoami/auth/adapter/in/KakaoOauthController.java
  src/main/java/com/dahhong/whoami/auth/adapter/in/swagger/KakaoOauthControllerSwagger.java
  src/main/java/com/dahhong/whoami/global/config/SwaggerConfig.java
  src/main/java/com/dahhong/whoami/global/security/SecurityConfig.java
Labels: documentation

#5 [Feat]: Kakao를 이용한 서비스 인증/인가 로직&문서화 완료
  build.gradle
  src/main/java/com/dahhong/whoami/auth/adapter/in/KakaoOauthController.java
  src/main/java/com/dahhong/whoami/auth/adapter/in/dto/KakaoCallbackResponseDto.java
  src/main/java/com/dahhong/whoami/auth/adapter/in/swagger/KakaoOauthControllerSwagger.java
  src/main/java/com/dahhong/whoami/auth/application/port/in/KakaoTokenRefreshUseCase.java
  src/main/java/com/dahhong/whoami/auth/application/port/in/LoginKakaoUseCase.java
  src/main/java/com/dahhong/whoami/auth/application/port/in/LogoutKakaoUseCase.java
  src/main/java/com/dahhong/whoami/auth/application/port/in/QuitKakaoUseCase.java
  src/main/java/com/dahhong/whoami/auth/application/service/GetKaKaoUserInfoService.java
  src/main/java/com/dahhong/whoami/auth/application/service/IdTokenService.java
  src/main/java/com/dahhong/whoami/auth/application/service/KakaoTokenRefreshService.java
  src/main/java/com/dahhong/whoami/auth/application/service/LoginKakaoService.java
  src/main/java/com/dahhong/whoami/auth/application/service/LogoutKakaoService.java
  src/main/java/com/dahhong/whoami/auth/application/service/QuitKakaoService.java
  src/main/java/com/dahhong/whoami/auth/application/service/UserDetailsServiceImpl.java
  src/main/java/com/dahhong/whoami/auth/application/service/dto/GetTokenResponseDto.java
  src/main/java/com/dahhong/whoami/auth/application/service/dto/IdTokenPayloadResponseDto.java
  src/main/java/com/dahhong/whoami/auth/application/service/dto/KakaoAccount.java
  src/main/java/com/dahhong/whoami/auth/application/service/dto/Profile.java
  src/main/java/com/dahhong/whoami/auth/application/service/dto/QuitKakaoResponseDto.java
  src/main/java/com/dahhong/whoami/auth/application/service/dto/TokenRefreshResponseDto.java
  src/main/java/com/dahhong/whoami/auth/application/service/dto/UserInfoResponseDto.java
  src/main/java/com/dahhong/whoami/auth/domain/entity/UserDetailsImpl.java
  src/main/java/com/dahhong/whoami/global/config/KaKaoRestTemplateConfig.java
  src/main/java/com/dahhong/whoami/global/config/SwaggerConfig.java
  src/main/java/com/dahhong/whoami/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dahhong/whoami/global/exception/customException/AuthorizationFailureException.java
  src/main/java/com/dahhong/whoami/global/response/ApiResponse.java
  src/main/java/com/dahhong/whoami/global/response/enums/ResultCode.java
  src/main/java/com/dahhong/whoami/global/security/SecurityConfig.java
  src/main/java/com/dahhong/whoami/global/security/authenticationProvider/KakaoAuthenticationProvider.java
  src/main/java/com/dahhong/whoami/global/security/filter/KakaoJwtAuthenticationFilter.java
  src/main/java/com/dahhong/whoami/global/security/filter/dto/AccessTokenVerificationResponseDto.java
  src/main/java/com/dahhong/whoami/user/adapter/out/UserCommandAdapter.java
  src/main/java/com/dahhong/whoami/user/adapter/out/UserQueryAdapter.java
  src/main/java/com/dahhong/whoami/user/application/port/in/GetUserUseCase.java
  src/main/java/com/dahhong/whoami/user/application/port/in/JoinKakaoUserUseCase.java
  src/main/java/com/dahhong/whoami/user/application/port/in/QuitUserUseCase.java
  src/main/java/com/dahhong/whoami/user/application/port/out/UserCommandPort.java
  src/main/java/com/dahhong/whoami/user/application/port/out/UserQueryPort.java
  src/main/java/com/dahhong/whoami/user/application/service/GetUserService.java
  src/main/java/com/dahhong/whoami/user/application/service/JoinKakaoUserService.java
  src/main/java/com/dahhong/whoami/user/application/service/QuitUserService.java
  src/main/java/com/dahhong/whoami/user/domain/entity/AuthType.java
  src/main/java/com/dahhong/whoami/user/domain/entity/Role.java
  src/main/java/com/dahhong/whoami/user/domain/entity/User.java
  src/main/java/com/dahhong/whoami/user/infrastructure/repository/UserRepository.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#7 [Feat]: Page CRUD
  src/main/java/com/dahhong/whoami/global/config/SwaggerConfig.java
  src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
  src/main/java/com/dahhong/whoami/page/adapter/in/dto/CreatePageResponseDto.java
  src/main/java/com/dahhong/whoami/page/adapter/in/dto/GetPageResponseDto.java
  src/main/java/com/dahhong/whoami/page/adapter/in/dto/PageRequestDto.java
  src/main/java/com/dahhong/whoami/page/adapter/in/swagger/PageControllerSwagger.java
  src/main/java/com/dahhong/whoami/page/adapter/out/PageCommandAdapter.java
  src/main/java/com/dahhong/whoami/page/adapter/out/PageQueryAdapter.java
  src/main/java/com/dahhong/whoami/page/application/port/in/CreatePageUseCase.java
  src/main/java/com/dahhong/whoami/page/application/port/in/DeletePageUseCase.java
  src/main/java/com/dahhong/whoami/page/application/port/in/GetPageUseCase.java
  src/main/java/com/dahhong/whoami/page/application/port/in/UpdatePageUseCase.java
  src/main/java/com/dahhong/whoami/page/application/port/out/PageCommandPort.java
  src/main/java/com/dahhong/whoami/page/application/port/out/PageQueryPort.java
  src/main/java/com/dahhong/whoami/page/application/service/CreatePageService.java
  src/main/java/com/dahhong/whoami/page/application/service/DeletePageService.java
  src/main/java/com/dahhong/whoami/page/application/service/GetPageService.java
  src/main/java/com/dahhong/whoami/page/application/service/UpdatePageService.java
  src/main/java/com/dahhong/whoami/page/domain/entity/Page.java
  src/main/java/com/dahhong/whoami/page/infrastructure/repository/PageRepository.java
  src/main/java/com/dahhong/whoami/user/domain/entity/User.java
Labels: enhancement

#8 feat: 유저 정보 조회 api 추가
  src/main/java/com/dahhong/whoami/global/security/SecurityConfig.java
  src/main/java/com/dahhong/whoami/user/adapter/in/UserController.java
  src/main/java/com/dahhong/whoami/user/adapter/in/dto/UserInfoDto.java
  src/main/java/com/dahhong/whoami/user/adapter/in/swagger/UserControllerSwagger.java
  src/main/java/com/dahhong/whoami/user/adapter/out/UserQueryAdapter.java
  src/main/java/com/dahhong/whoami/user/application/port/in/GetUserUseCase.java
  src/main/java/com/dahhong/whoami/user/application/port/out/UserQueryPort.java
  src/main/java/com/dahhong/whoami/user/application/service/GetUserService.java
Labels: new feature

#11 [Fix]: Authentication Provider Supports method가 항상 false를 리턴하는 버그 수정
  src/main/java/com/dahhong/whoami/global/security/authenticationProvider/KakaoAuthenticationProvider.java
  src/main/java/com/dahhong/whoami/global/security/filter/KakaoJwtAuthenticationFilter.java
  src/main/java/com/dahhong/whoami/global/security/filter/UserAuthentication.java
  src/main/java/com/dahhong/whoami/user/domain/entity/Role.java
Labels: bug
